settings:
  language_mapping:
    ar: ar-SA
    da: da
    de: de-DE
    en_AU: en-AU
    en_CA: en-CA
    en_GB: en-GB
    en_US: en-US
    es: es-ES
    es_MX: es-MX
    fr: fr-FR
    it: it
    ja: ja
    nl: nl-NL

filters:

  - filter_type: file
    source_language: en
    source_file: fastlane/metadata/en-US/release_notes.txt
    file_format: TXT
    translation_files_expression: 'fastlane/metadata/<lang>/release_notes.txt'