language: objective-c

os: osx
osx_image: xcode8

env:
  global:
    - XCWORKSPACE="Fuzi.xcworkspace"
    - IOS_SCHEME="Fuzi-iOS"
    - OSX_SCHEME="Fuzi-OSX"
    - TVOS_SCHEME="Fuzi-tvOS"
    - WATCHOS_SCHEME="Fuzi-WatchOS"
  matrix:
    - DESTINATION="platform=macOS,arch=x86_64" SCHEME="$OSX_SCHEME" SDK="macosx" ACTION="test"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7" SCHEME="$IOS_SCHEME" SDK="iphonesimulator" ACTION="test"
    - DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p" SCHEME="$TVOS_SCHEME" SDK="appletvsimulator" ACTION="test"
    - DESTINATION="name=Apple Watch - 38mm" SCHEME="$WATCHOS_SCHEME" SDK="watchsimulator" ACTION="build"

script:
- xcodebuild -workspace "$XCWORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -sdk $SDK $ACTION

