[package]
name = "nss"
version = "0.1.0"
authors = ["application-services@mozilla.com"]
edition = "2018"
license = "MPL-2.0"

[lib]
crate-type = ["lib"]

[dependencies]
base64 = "0.11.0"
error-support = { path = "../../error" }
failure = "0.1.6"
failure_derive = "0.1.5"
nss_sys = { path = "nss_sys" }
serde = "1.0.104"
serde_derive = "1.0.104"
