name: Build and publish ComponentLibrary DocC
on:
  workflow_dispatch: # Allow manual runs
  push:
    branches:
      - main
    paths: # Only runs on changes to BrowserKit files
      - BrowserKit/Sources/ComponentLibrary/**
      - .github/workflows/firefox-ios-publish-docc.yml

permissions:
  contents: read
  pages: write
  id-token: write # Uses GitHub API to get GitHub Pages configuration outputs

concurrency:
  group: github-pages
  cancel-in-progress: true # Allow just the most recent deployment

jobs:
  docs:
    runs-on: macos-26
    strategy:
      matrix:
        xcode: ["26.1"]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Switch to Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build DocC
        run: |
          xcodebuild docbuild -project firefox-ios/Client.xcodeproj \
            -scheme ComponentLibrary \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';
          xcrun docc process-archive transform-for-static-hosting \
            /tmp/docbuild/Build/Products/Debug-iphoneos/ComponentLibrary.doccarchive \
            --hosting-base-path "firefox-ios" \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/componentlibrary\"</script>" > docs/index.html;
      - name: Store docs artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload only docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
