name: Merge Unit Tests

on:
  pull_request:
    branches: [ main, mob-3113-firefox-upgrade-133 ]

jobs:
  execute_merge_tests:
    runs-on: macos-14
    name: Execute Merge Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare_environment
        with:
          core-token: ${{ secrets.IOS_CORE_TOKEN }}

      - name: Perform Unit Tests and Publish Test reports
        id: perform-tests
        uses: ./.github/actions/perform_unit_tests
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}